---
R2:
    hostname: "16.16.16.2"
    port: 830
    groups:
    - cisco_group
    location: "UK"

R3:
    hostname: "16.16.16.3"
    port: 830
    groups:
      - cisco_group
    location: "US"

R4:
    hostname: "16.16.16.4"
    port: 830
    groups:
      - cisco_group
    location: "Canada"